[package]
name = "doommy"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.1"
pest_derive = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
clap = { version = "4.5.21", features = ["derive"] }
